
  create table "public"."play_data" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null default auth.uid(),
    "updated_at" timestamp with time zone not null default now(),
    "video_id" text not null,
    "position" bigint default '0'::bigint,
    "duration" bigint default '0'::bigint
      );


alter table "public"."play_data" enable row level security;

CREATE UNIQUE INDEX play_data_pkey ON public.play_data USING btree (id);

CREATE UNIQUE INDEX play_data_user_video_unique ON public.play_data USING btree (user_id, video_id);

alter table "public"."play_data" add constraint "play_data_pkey" PRIMARY KEY using index "play_data_pkey";

alter table "public"."play_data" add constraint "play_data_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(uuid) not valid;

alter table "public"."play_data" validate constraint "play_data_user_id_fkey";

alter table "public"."play_data" add constraint "play_data_user_video_unique" UNIQUE using index "play_data_user_video_unique";

grant delete on table "public"."play_data" to "anon";

grant insert on table "public"."play_data" to "anon";

grant references on table "public"."play_data" to "anon";

grant select on table "public"."play_data" to "anon";

grant trigger on table "public"."play_data" to "anon";

grant truncate on table "public"."play_data" to "anon";

grant update on table "public"."play_data" to "anon";

grant delete on table "public"."play_data" to "authenticated";

grant insert on table "public"."play_data" to "authenticated";

grant references on table "public"."play_data" to "authenticated";

grant select on table "public"."play_data" to "authenticated";

grant trigger on table "public"."play_data" to "authenticated";

grant truncate on table "public"."play_data" to "authenticated";

grant update on table "public"."play_data" to "authenticated";

grant delete on table "public"."play_data" to "postgres";

grant insert on table "public"."play_data" to "postgres";

grant references on table "public"."play_data" to "postgres";

grant select on table "public"."play_data" to "postgres";

grant trigger on table "public"."play_data" to "postgres";

grant truncate on table "public"."play_data" to "postgres";

grant update on table "public"."play_data" to "postgres";

grant delete on table "public"."play_data" to "service_role";

grant insert on table "public"."play_data" to "service_role";

grant references on table "public"."play_data" to "service_role";

grant select on table "public"."play_data" to "service_role";

grant trigger on table "public"."play_data" to "service_role";

grant truncate on table "public"."play_data" to "service_role";

grant update on table "public"."play_data" to "service_role";


  create policy "Users can insert own play_data"
  on "public"."play_data"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can read own play_data"
  on "public"."play_data"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Users can update own play_data"
  on "public"."play_data"
  as permissive
  for update
  to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



